### ISSUE TITLE
Consider providing consumer proguard rules for ViewBinding.inflate and ViewBinding.bind

### ISSUE THREAD

**Issue by Zhuinden** [yogacp/android-viewbinding#1]
Currently, using release build with this library would fail without additional Proguard configuration.

```
-keep public class * extends androidx.viewbinding.ViewBinding
```

**Comment by yogacp** [comment]
Hi @Zhuinden, sorry for the late reply. Lately, I try to implement proguard using this lib. use these rules:
`-keep class * implements androidx.viewbinding.ViewBinding {
    public static *** bind(android.view.View);
    public static *** inflate(android.view.LayoutInflater);
}`
