### ISSUE TITLE
Milestone to support Dialog and support onDestroy lifecycle to reduce leak memory?

### ISSUE THREAD

**Issue by mochadwi** [yogacp/android-viewbinding#2]
Any exact milestone to add support for dialog?

I'm searching a references library, looks like it's the same with yours:

https://github.com/kirich1409/ViewBindingPropertyDelegate & https://github.com/hoc081098/ViewBindingDelegate

**Comment by yogacp** [comment]
Hi @mochadwi , thanks for your concern. for the dialogfragment milestone, actually, it should be done at the end of this year. 
and thanks for your suggestion about the onDestroy lifecycle, I will add it in the next release for the activity and the bottomsheet.

**Comment by yogacp** [comment]
Hi @mochadwi , 
Thank you for waiting for an update, and sorry for waiting too long. Please do update to the latest version **1.0.3**. And let me know if there is still an issue. Also, I add a capability to support the DialogFragment too.
