### ISSUE TITLE
Bug using `com.google.android.gms.maps.MapView`

### ISSUE THREAD

**Issue by JBlaz** [yogacp/android-viewbinding#3]
This works except in that case that the view requires a method to be called in `onDestroyView`. The delegate nullifies the binding in `onDestroy` which is before `onDestroyView`.

For example `com.google.android.gms.maps.MapView` requires that calling fragments and activities forward the call to `onDestroyView` to the view itself. Doing this as described in the documentation [here](https://developers.google.com/android/reference/com/google/android/gms/maps/MapView) results in a crash on the bindling line
```
override fun onDestroyView() {
    binding.map.onDestroy()
    super.onDestroyView()
}
```
With the message:
`Cannot access view bindings. View lifecycle is DESTROYED!`

This is what is expected when looking at the code but the binding should be available until after `onDestroyView`, not `onDestroy` which is what the current implementation does.

**Comment by JBlaz** [comment]
Sorry, this is a bug I have but I still would like to know how to have access to the binding before the end of onDestroyView

EDIT:

Actually it still crashes when placing the call in onDestory. Since it is obviously later in the stack

**Comment by yogacp** [comment]
Hi @JBlaz, Thank you for your issue. Currently, it still in my timeline to fix this. But, it may take more time since I have other projects to do.

**Comment by yogacp** [comment]
Or maybe you want to contribute to this library, you can create a Pull Request, it would be my pleasure.
