### ISSUE TITLE
viewBinding Activity delegate - App Crash

### ISSUE THREAD

**Issue by stevdza-san** [yogacp/android-viewbinding#4]
This is my simple activity: 

```
class MainActivity : AppCompatActivity() {

    private val binding by viewBinding<ActivityMainBinding>()

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        binding.button.text = "Some Text"
    }

}
```

And I always get an error when launch the app:

> 2021-03-29 09:21:23.487 15441-15441/? E/example.testap: Unknown bits set in runtime_flags: 0x8000
> 2021-03-29 09:21:23.996 15441-15441/com.example.testapp E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.example.testapp, PID: 15441
>     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.testapp/com.example.testapp.MainActivity}: java.lang.reflect.InvocationTargetException
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
>      Caused by: java.lang.reflect.InvocationTargetException
>         at java.lang.reflect.Method.invoke(Native Method)
>         at android.viewbinding.library.activity.ActivityViewBindingDelegate.getValue(ActivityBinding.kt:38)
>         at com.example.testapp.MainActivity.getBinding(Unknown Source:10)
>         at com.example.testapp.MainActivity.onCreate(MainActivity.kt:16)
>         at android.app.Activity.performCreate(Activity.java:7802)
>         at android.app.Activity.performCreate(Activity.java:7791)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409) 
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
>         at android.os.Handler.dispatchMessage(Handler.java:107) 
>         at android.os.Looper.loop(Looper.java:214) 
>         at android.app.ActivityThread.main(ActivityThread.java:7356) 
>         at java.lang.reflect.Method.invoke(Native Method) 
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
>      Caused by: android.view.InflateException: Binary XML file line #9 in com.example.testapp:layout/activity_main: Binary XML file line #9 in com.example.testapp:layout/activity_main: Error inflating class fragment
>      Caused by: android.view.InflateException: Binary XML file line #9 in com.example.testapp:layout/activity_main: Error inflating class fragment
>      Caused by: java.lang.IllegalArgumentException: Binary XML file line #9: Duplicate id 0x7f0a010f, tag null, or parent id 0xffffffff with another fragment for androidx.navigation.fragment.NavHostFragment
>         at androidx.fragment.app.FragmentLayoutInflaterFactory.onCreateView(FragmentLayoutInflaterFactory.java:116)
>         at androidx.fragment.app.FragmentController.onCreateView(FragmentController.java:135)
>         at androidx.fragment.app.FragmentActivity.dispatchFragmentsOnCreateView(FragmentActivity.java:356)
>         at androidx.fragment.app.FragmentActivity.onCreateView(FragmentActivity.java:335)
>         at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1069)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:997)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
>         at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
>         at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:682)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
>         at com.example.testapp.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:43)
>         at com.example.testapp.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:37)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at android.viewbinding.library.activity.ActivityViewBindingDelegate.getValue(ActivityBinding.kt:38)
>         at com.example.testapp.MainActivity.getBinding(Unknown Source:10)
>         at com.example.testapp.MainActivity.onCreate(MainActivity.kt:16)
>         at android.app.Activity.performCreate(Activity.java:7802)
>         at android.app.Activity.performCreate(Activity.java:7791)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
> 2021-03-29 09:21:23.997 15441-15441/com.example.testapp E/AndroidRuntime:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
>         at android.os.Handler.dispatchMessage(Handler.java:107)
>         at android.os.Looper.loop(Looper.java:214)
>         at android.app.ActivityThread.main(ActivityThread.java:7356)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
>

**Comment by yogacp** [comment]
Hi @stevdza-san , Thank you for your issue.

Based on your stacktrace, I see that you are using XML layout with fragment inside it. and you are using `setContentView`. So it cause a duplicate inflating layout. you can remove the setContentView, and try to re-build again.

**Comment by yogacp** [comment]
If you are using activity as a parent for your fragment, no need to use `by viewBinding()` if there is no interaction needed in your activity layout. you can directly use the `setContentView()`.

**Comment by stevdza-san** [comment]
@yogacp Yep it works. Thank you for fast response :)
